name: Update data

on:
  schedule:
    - cron: '4 2 * * 4'  # 2:04 on Thursdays
  branches:
    - 'gh-pages'
# on: push

jobs:
  update_caption_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
    - name: debug
      run: |
        ls
    - name: Setup environment
      run: |
        pip install -r requirements.txt
    - name: Get caption contest IDs
      run: |
        cd nyccwinners; python get_nycc_winners.py; cd ..
        git add nyccwinners/nyc_winners.json
    - name: Download data
      env:
        CCD_IP: ${{ secrets.CCD_IP }}
        CCD_MACHINE: ${{ secrets.CCD_MACHINE }}
        FOO: bar
      run: |
        env | grep CCD
        python download_dashboards.py
        export C=$(python -c "import download_dashboards as d; print(d.get_latest_contest())")
        git add summaries/$C.csv cartoons/$C.jpg  # only 1 contest added as specified in download-dashboards.py
    - name: Integrate data
      run: |
        python write-html.py
        git add dashboards/*.html
        git add index.html
    - name: Push
      run: |
          git status
          git config --global user.name 'github-actions-bot'
          git config --global user.email '947546838+github-actions[bot]@users.noreply.github.com'
          git commit -m "Update caption contest data"
          git push
